//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyuncuTabani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Futbolcu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Futbolcu()
        {
            this.Kayit = new HashSet<Kayit>();
        }
    
        public int FutbolcuID { get; set; }
        public string Fadi { get; set; }
        public string Fsoyadi { get; set; }
        public Nullable<System.DateTime> Dtarih { get; set; }
        public string Fmevki { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kayit> Kayit { get; set; }
    }
}
