//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyuncuTabani.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int KayitID { get; set; }
        public Nullable<int> FutbolcuID { get; set; }
        public Nullable<int> TakimID { get; set; }
    
        public virtual Futbolcu Futbolcu { get; set; }
        public virtual Takim Takim { get; set; }
    }
}
