//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OyuncuTabani.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OyuncuTabaniEntities : DbContext
    {
        public OyuncuTabaniEntities()
            : base("name=OyuncuTabaniEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Futbolcu> Futbolcu { get; set; }
        public virtual DbSet<Kayit> Kayit { get; set; }
        public virtual DbSet<Takim> Takim { get; set; }
    }
}
